### PR TITLE
Fix get gauges query

### PR DESCRIPTION
**Pull request by teddyknox**

### CODE REVIEW

**Review by jcompagni10 — APPROVED** [review]

**Review by jcompagni10 — DISMISSED** [review]

**Review by dib542 — COMMENTED** [review]
It looks like filtering by denom is broken and pagination is now (or always was) broken on this endpoint.

in this test I added:
```
dualityd tx incentives create-gauge "tokenD<>tokenE" 1 20000 1000tokenD,1000tokenE 10000 1000 --from fred --keyring-backend test --broadcast-mode block -y
dualityd tx incentives create-gauge "tokenD<>tokenF" 1 20000 1000tokenD,1000tokenF 10000 1000 --from fred --keyring-backend test --broadcast-mode block -y
dualityd tx incentives create-gauge "tokenD<>tokenF" [-100] 2000 1000tokenD,1000tokenF 10000 1000 --from fred --keyring-backend test --broadcast-mode block -y
```

if I request 2 records: `http://localhost:1317/dualitylabs/duality/incentives/v1beta1/gauges?status=0&pagination.limit=2&pagination.count_total=true`
I get 
```json
{
  "gauges": [
    {
      "id": "1",
      "is_perpetual": false,
      "distribute_to": {
        "pairID": {
          "token0": "tokenD",
          "token1": "tokenF"
        },
        "startTick": "-100",
        "endTick": "2000"
      },
      "coins": [
        {
          "denom": "tokenD",
          "amount": "1000"
        },
        {
          "denom": "tokenF",
          "amount": "1000"
        }
      ],
      "start_time": "1970-01-01T00:00:00Z",
      "num_epochs_paid_over": "10000",
      "filled_epochs": "0",
      "distributed_coins": [
      ],
      "pricing_tick": "1000"
    },
    {
      "id": "2",
      "is_perpetual": false,
      "distribute_to": {
        "pairID": {
          "token0": "tokenD",
          "token1": "tokenF"
        },
        "startTick": "1",
        "endTick": "20000"
      },
      "coins": [
        {
          "denom": "tokenD",
          "amount": "1000"
        },
        {
          "denom": "tokenF",
          "amount": "1000"
        }
      ],
      "start_time": "1970-01-01T00:00:00Z",
      "num_epochs_paid_over": "10000",
      "filled_epochs": "0",
      "distributed_coins": [
      ],
      "pricing_tick": "1000"
    },
    {
      "id": "3",
      "is_perpetual": false,
      "distribute_to": {
        "pairID": {
          "token0": "tokenD",
          "token1": "tokenE"
        },
        "startTick": "1",
        "endTick": "20000"
      },
      "coins": [
        {
          "denom": "tokenD",
          "amount": "1000"
        },
        {
          "denom": "tokenE",
          "amount": "1000"
        }
      ],
      "start_time": "1970-01-01T00:00:00Z",
      "num_epochs_paid_over": "10000",
      "filled_epochs": "0",
      "distributed_coins": [
      ],
      "pricing_tick": "1000"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "1"
  }
}
```
so the pagination is being ignored or is always resolving to "1 record"

It looks like filtering by denom no longer works:
querying `http://localhost:1317/dualitylabs/duality/incentives/v1beta1/gauges?status=0&denom=DualityPoolShares-tokenD-tokenF-t31-f30`
gives
```json
{
  "code": 2,
  "message": "runtime error: invalid memory address or nil pointer dereference: panic",
  "details": [
  ]
}
```

To be clear, I don't need filtering by denom to work. it's not needed by the frontend and you could consider removing it.

I think the Pagination should be fixed or removed (some of our other endpoints don't support pagination at all, and this could be one of them). It would be problematic if the pagination is not working and the number of gauges exceeds the number of records that the server is willing to send out in one page.

I strongly recommend to fix if easy to do so, but I can deal with this being a future fix (in which case please write it down in a backlog)

**Review by dib542 — APPROVED** [review]
I think the dev container changes should probably live in a different PR because they look like interesting additions to the work environment but are unrelated to the change.

**Comment by dib542** [comment]
The tests seem to be failing. although I don't see any failures there's a comment about `x/incentives/client/cli/cli_test.go:65:5: unknown field 'Pagination' in struct literal of type "github.com/duality-labs/duality/x/incentives/types".GetGaugesRequest`

So I think we could delete all references to `Pagination` in `x/incentives/client/cli/cli_test.go`

**Comment by dib542** [comment]
☝️ got tests passing

**Review by dib542 — APPROVED** [review]

**Comment by teddyknox** [comment]
Thanks @dib542

**Pull request merged**
